version: "3.9"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: develop
      MYSQL_USER: devel
      MYSQL_PASSWORD: devel
      MYSQL_DATABASE: demo
    ports:
      - "3307:3306"
    networks:
      - product_api_network
  web:
    image: nginx:latest
    volumes:
      - ./app/public:/code/public
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - product_api_network
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9001:80"
    environment:
      PMA_HOST: db
    networks:
      - product_api_network
  php:
    build:
      context: .
      dockerfile: docker/php/fpm/Dockerfile
    volumes:
      - ./app:/code
    networks:
      - product_api_network
      - elastic
  php-cli:
    build:
      dockerfile: docker/php/cli/Dockerfile
    volumes:
      - ./app:/code
    networks:
      - product_api_network
      - elastic
  redis:
    image: redis:latest
    networks:
      - product_api_network

  ## elastic serach
  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
## volumes
volumes:
  es_data:
    driver: local

## networks
networks:
  product_api_network:
    name: product_api_network
  elastic:
    name: elastic